### ISSUE TITLE
user is registered but isnt

### ISSUE THREAD

**Issue by Volas171** [ControlPanel-gg/dashboard#180]
**Describe the bug 🐛**
basically when you try to register an account you cant since you get a fancy error saying there's already one

**To Reproduce**
1. Go to '/register'
2. Fill the info
3. Register

**Expected behavior**
It should say that there's none, infact I have checked both MySQL and panel and user isn't registered

**Screenshots**
![image](https://user-images.githubusercontent.com/60143910/131388916-48e1622d-af50-4d6a-8ddc-0703137cc1a9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10/ Debian Linux 10 LTS
 - Browser Mozilla Firefox/GoogleChrome
 - Version lastest as of 30/08/2021

**Additional context**

```
● dashboard.service - Dashboard Queue Worker
   Loaded: loaded (/etc/systemd/system/dashboard.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2021-08-30 18:10:03 UTC; 28min ago
 Main PID: 2630 (php)
    Tasks: 1 (limit: 4698)
   Memory: 33.4M
   CGroup: /system.slice/dashboard.service
           └─2630 /usr/bin/php /var/www/dashboard/artisan queue:work --sleep=3 --tries=3

Aug 30 18:15:08 UwU php[2630]: [2021-08-30 18:15:08][83] Processing: App\Notifications\Auth\QueuedVerifyEmail
Aug 30 18:15:09 UwU php[2630]: [2021-08-30 18:15:09][83] Processed:  App\Notifications\Auth\QueuedVerifyEmail
Aug 30 18:32:46 UwU php[2630]: [2021-08-30 18:32:46][84] Processing: App\Notifications\Auth\QueuedVerifyEmail
Aug 30 18:32:46 UwU php[2630]: [2021-08-30 18:32:46][84] Processed:  App\Notifications\Auth\QueuedVerifyEmail
Aug 30 18:35:35 UwU php[2630]: [2021-08-30 18:35:35][85] Processing: App\Notifications\Auth\QueuedVerifyEmail
Aug 30 18:35:36 UwU php[2630]: [2021-08-30 18:35:36][85] Processed:  App\Notifications\Auth\QueuedVerifyEmail
Aug 30 18:36:39 UwU php[2630]: [2021-08-30 18:36:39][86] Processing: App\Notifications\WelcomeMessage
**Aug 30 18:36:39 UwU php[2630]: [2021-08-30 18:36:39][86] Failed:     App\Notifications\WelcomeMessage**

```

**Comment by RamonRobben** [comment]
Have you tested your panel on the same domain before? I think ControlPanel saves a cookie and your ip address to the database to check if a user has already been registered. So you might want to clear your cookies and try again.

**Comment by Volas171** [comment]
havent used pterodactyl panel on the same domain, tried cleaning up cookies, nothing same error

**Comment by Volas171** [comment]
```
root@UwU:/var/www/dashboard# tail -n 100 /var/www/dashboard/storage/logs/laravel.log
[2021-08-29 23:09:08] production.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'holaquease97547@gmail.com' for key 'users_email_unique' (SQL: insert into `users` (`name`, `email`, `role`, `password`, `pterodactyl_id`, `updated_at`, `created_at`) values (Volas, holaquease97547@gmail.com, admin, $2y$10$w6ygDkoHguHzZgVo5xf/wu4KwylFYFavRNmuzHnJZ3u6szdvARB4y, 2, 2021-08-29 23:09:07, 2021-08-29 23:09:07)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'holaquease97547@gmail.com' for key 'users_email_unique' (SQL: insert into `users` (`name`, `email`, `role`, `password`, `pterodactyl_id`, `updated_at`, `created_at`) values (Volas, holaquease97547@gmail.com, admin, $2y$10$w6ygDkoHguHzZgVo5xf/wu4KwylFYFavRNmuzHnJZ3u6szdvARB4y, 2, 2021-08-29 23:09:07, 2021-08-29 23:09:07)) at /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Connection.php:685)
[stacktrace]
#0 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Connection.php(645): Illuminate\\Database\\Connection->runQueryCallback()
#1 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Connection.php(479): Illuminate\\Database\\Connection->run()
#2 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Connection.php(431): Illuminate\\Database\\Connection->statement()
#3 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\\Database\\Connection->insert()
#4 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2997): Illuminate\\Database\\Query\\Processors\\Processor->processInsertGetId()
#5 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1648): Illuminate\\Database\\Query\\Builder->insertGetId()
#6 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1123): Illuminate\\Database\\Eloquent\\Builder->__call()
#7 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1088): Illuminate\\Database\\Eloquent\\Model->insertAndSetId()
#8 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(929): Illuminate\\Database\\Eloquent\\Model->performInsert()
#9 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(904): Illuminate\\Database\\Eloquent\\Model->save()
#10 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Support/helpers.php(263): Illuminate\\Database\\Eloquent\\Builder->Illuminate\\Database\\Eloquent\\{closure}()
#11 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(905): tap()
#12 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->create()
#13 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1991): Illuminate\\Database\\Eloquent\\Model->forwardCallTo()
#14 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2003): Illuminate\\Database\\Eloquent\\Model->__call()
#15 /var/www/dashboard/app/Console/Commands/MakeUserCommand.php(67): Illuminate\\Database\\Eloquent\\Model::__callStatic()
#16 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\MakeUserCommand->handle()
#17 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#18 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#19 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#20 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Container/Container.php(614): Illuminate\\Container\\BoundMethod::call()
#21 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#22 /var/www/dashboard/vendor/symfony/console/Command/Command.php(288): Illuminate\\Console\\Command->execute()
#23 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#24 /var/www/dashboard/vendor/symfony/console/Application.php(974): Illuminate\\Console\\Command->run()
#25 /var/www/dashboard/vendor/symfony/console/Application.php(291): Symfony\\Component\\Console\\Application->doRunCommand()
#26 /var/www/dashboard/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun()
#27 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run()
#28 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#29 /var/www/dashboard/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#30 {main}

[previous exception] [object] (PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'holaquease97547@gmail.com' for key 'users_email_unique' at /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Connection.php:478)
[stacktrace]
#0 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Connection.php(478): PDOStatement->execute()
#1 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Connection.php(678): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#2 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Connection.php(645): Illuminate\\Database\\Connection->runQueryCallback()
#3 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Connection.php(479): Illuminate\\Database\\Connection->run()
#4 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Connection.php(431): Illuminate\\Database\\Connection->statement()
#5 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\\Database\\Connection->insert()
#6 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2997): Illuminate\\Database\\Query\\Processors\\Processor->processInsertGetId()
#7 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1648): Illuminate\\Database\\Query\\Builder->insertGetId()
#8 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1123): Illuminate\\Database\\Eloquent\\Builder->__call()
#9 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1088): Illuminate\\Database\\Eloquent\\Model->insertAndSetId()
#10 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(929): Illuminate\\Database\\Eloquent\\Model->performInsert()
#11 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(904): Illuminate\\Database\\Eloquent\\Model->save()
#12 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Support/helpers.php(263): Illuminate\\Database\\Eloquent\\Builder->Illuminate\\Database\\Eloquent\\{closure}()
#13 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(905): tap()
#14 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->create()
#15 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1991): Illuminate\\Database\\Eloquent\\Model->forwardCallTo()
#16 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2003): Illuminate\\Database\\Eloquent\\Model->__call()
#17 /var/www/dashboard/app/Console/Commands/MakeUserCommand.php(67): Illuminate\\Database\\Eloquent\\Model::__callStatic()
#18 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\MakeUserCommand->handle()
#19 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#20 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#21 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#22 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Container/Container.php(614): Illuminate\\Container\\BoundMethod::call()
#23 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#24 /var/www/dashboard/vendor/symfony/console/Command/Command.php(288): Illuminate\\Console\\Command->execute()
#25 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#26 /var/www/dashboard/vendor/symfony/console/Application.php(974): Illuminate\\Console\\Command->run()
#27 /var/www/dashboard/vendor/symfony/console/Application.php(291): Symfony\\Component\\Console\\Application->doRunCommand()
#28 /var/www/dashboard/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun()
#29 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run()
#30 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#31 /var/www/dashboard/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#32 {main}
"}

```

**Comment by Volas171** [comment]
heres the output of laravel error log

```
[previous exception] [object] (PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'randomusername@gmail.com' for key 'users_email_unique' at /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Connection.php:478)
[stacktrace]
#0 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Connection.php(478): PDOStatement->execute()
#1 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Connection.php(678): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#2 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Connection.php(645): Illuminate\\Database\\Connection->runQueryCallback()
#3 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Connection.php(479): Illuminate\\Database\\Connection->run()
#4 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Connection.php(431): Illuminate\\Database\\Connection->statement()
#5 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\\Database\\Connection->insert()
#6 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2997): Illuminate\\Database\\Query\\Processors\\Processor->processInsertGetId()
#7 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1648): Illuminate\\Database\\Query\\Builder->insertGetId()
#8 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1123): Illuminate\\Database\\Eloquent\\Builder->__call()
#9 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1088): Illuminate\\Database\\Eloquent\\Model->insertAndSetId()
#10 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(929): Illuminate\\Database\\Eloquent\\Model->performInsert()
#11 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(904): Illuminate\\Database\\Eloquent\\Model->save()
#12 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Support/helpers.php(263): Illuminate\\Database\\Eloquent\\Builder->Illuminate\\Database\\Eloquent\\{closure}()
#13 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(905): tap()
#14 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->create()
#15 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1991): Illuminate\\Database\\Eloquent\\Model->forwardCallTo()
#16 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2003): Illuminate\\Database\\Eloquent\\Model->__call()
#17 /var/www/dashboard/app/Console/Commands/MakeUserCommand.php(67): Illuminate\\Database\\Eloquent\\Model::__callStatic()
#18 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\MakeUserCommand->handle()
#19 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#20 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#21 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#22 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Container/Container.php(614): Illuminate\\Container\\BoundMethod::call()
#23 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#24 /var/www/dashboard/vendor/symfony/console/Command/Command.php(288): Illuminate\\Console\\Command->execute()
#25 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#26 /var/www/dashboard/vendor/symfony/console/Application.php(974): Illuminate\\Console\\Command->run()
#27 /var/www/dashboard/vendor/symfony/console/Application.php(291): Symfony\\Component\\Console\\Application->doRunCommand()
#28 /var/www/dashboard/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun()
#29 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run()
#30 /var/www/dashboard/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#31 /var/www/dashboard/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#32 {main}
"}

```

**Comment by RamonRobben** [comment]
Yeah from the error log it looks like there is already a user registered with email address hola[redacted]97547@gmail.com
I redacted some info for privacy reasons.

**Comment by Volas171** [comment]
yeah but the fun fact is that theres no one using that email

**Comment by Volas171** [comment]
![image](https://user-images.githubusercontent.com/60143910/131392629-ad07ab1e-1055-4ba7-83f2-39535c80de5b.png)

**Comment by RamonRobben** [comment]
@Volas171 The screenshot you're showing is not ControlPanel.gg but pterodactyl. Can you check if there are any users in the database that you use for controlpanel?

**Comment by Volas171** [comment]
![image](https://user-images.githubusercontent.com/60143910/131392999-1c4c7838-5bc4-41e8-bf62-96eef163cde1.png)

**Comment by RamonRobben** [comment]
I can see there are 6 users (6 total entries). Have you already registered at least once on your website?

**Comment by Volas171** [comment]
i have tried, the manual way using 
**php artisan make:user** works
but tried on the controlpanel with another alternative email that is not registered on pterodactyl, neither the panel and it said error, account is registered

**Comment by RamonRobben** [comment]
@Volas171 Have you logged in to one of those accounts? Or have you created your own account manually and then logged into the account?

If that is the case you might want to check if your IP matches one the the IPs on the accounts. You can also turn this spam protection off in the .env file.

**Comment by Volas171** [comment]
i have logged into them

ok thank you, will try removing from .env

**Comment by RamonRobben** [comment]
@Volas171 Yeah If I am correct once your IP is associated to a account then you can't make another account with the same IP. This is just to stop people from making multiple accounts.

**Comment by Volas171** [comment]
how can it be disabled from .env tho

**Comment by RamonRobben** [comment]
By default, we only allow users to make one account per IP address. to disable this, head to /admin/configurations and set REGISTER_IP_CHECK to false. If you have proxied your domain through Cloudflare, then this check will always fail!
