### ISSUE TITLE
[Bug]: Email verification not sending email

### ISSUE THREAD

**Issue by Indoraptor1** [ControlPanel-gg/dashboard#794]
### What is your request about?

Hello,
My users are recieving email verifications, BUT if i send the notification they recive it via email too, so it is not an smtp problem (as far sa i know).

### Branch

main

### Controlpanel Logs

```Shell
array (
    'column' => '6',
    'dir' => 'desc',
  ),
)
[2023-04-18 21:59:02] production.ERROR: Settings Error: Could not load settings from database. The Installation probably is not done yet.
[2023-04-18 21:59:02] production.ERROR: ErrorException: file_put_contents(/var/www/controlpanel/storage/framework/cache/data/ee/2f/ee2f842aa7bb1f53edf3a2ed2c09a1807ffa6c90): Failed to open stream: Permission denied in /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:190
Stack trace:
#0 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(266): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#2 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(190): file_put_contents()
#3 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(77): Illuminate\Filesystem\Filesystem->put()
#4 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(200): Illuminate\Cache\FileStore->put()
#5 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(367): Illuminate\Cache\FileStore->forever()
#6 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Queue/Console/RestartCommand.php(67): Illuminate\Cache\Repository->forever()
#7 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Queue\Console\RestartCommand->handle()
#8 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#9 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#10 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#11 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Container/Container.php(663): Illuminate\Container\BoundMethod::call()
#12 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call()
#13 /var/www/controlpanel/vendor/symfony/console/Command/Command.php(312): Illuminate\Console\Command->execute()
#14 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Console/Command.php(152): Symfony\Component\Console\Command\Command->run()
#15 /var/www/controlpanel/vendor/symfony/console/Application.php(1022): Illuminate\Console\Command->run()
#16 /var/www/controlpanel/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand()
#17 /var/www/controlpanel/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun()
#18 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\Component\Console\Application->run()
#19 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Console/Application.php(194): Illuminate\Console\Application->run()
#20 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(336): Illuminate\Console\Application->call()
#21 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): Illuminate\Foundation\Console\Kernel->call()
#22 /var/www/controlpanel/app/Providers/AppServiceProvider.php(109): Illuminate\Support\Facades\Facade::__callStatic()
#23 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Providers\AppServiceProvider->boot()
#24 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#25 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#26 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#27 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Container/Container.php(663): Illuminate\Container\BoundMethod::call()
#28 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(933): Illuminate\Container\Container->call()
#29 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(914): Illuminate\Foundation\Application->bootProvider()
#30 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}()
#31 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(915): array_walk()
#32 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#33 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(242): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap()
#34 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Foundation\Application->bootstrapWith()
#35 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(160): Illuminate\Foundation\Http\Kernel->bootstrap()
#36 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#37 /var/www/controlpanel/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle()
#38 {main}
[2023-04-22 02:11:07] production.ERROR: Settings Error: Could not load settings from database. The Installation probably is not done yet.
[2023-04-22 02:11:07] production.ERROR: UnexpectedValueException: FilesystemIterator::__construct(/var/www/controlpanel/storage/framework/cache/data/ee): Failed to open directory: No such file or directory in /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:714
Stack trace:
#0 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(714): FilesystemIterator->__construct()
#1 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(230): Illuminate\Filesystem\Filesystem->deleteDirectory()
#2 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(678): Illuminate\Cache\FileStore->flush()
#3 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Cache/Console/ClearCommand.php(80): Illuminate\Cache\Repository->__call()
#4 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Cache\Console\ClearCommand->handle()
#5 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#7 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#8 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Container/Container.php(663): Illuminate\Container\BoundMethod::call()
#9 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call()
#10 /var/www/controlpanel/vendor/symfony/console/Command/Command.php(312): Illuminate\Console\Command->execute()
#11 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Console/Command.php(152): Symfony\Component\Console\Command\Command->run()
#12 /var/www/controlpanel/vendor/symfony/console/Application.php(1022): Illuminate\Console\Command->run()
#13 /var/www/controlpanel/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand()
#14 /var/www/controlpanel/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun()
#15 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\Component\Console\Application->run()
#16 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Console/Application.php(194): Illuminate\Console\Application->run()
#17 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(336): Illuminate\Console\Application->call()
#18 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): Illuminate\Foundation\Console\Kernel->call()
#19 /var/www/controlpanel/app/Providers/AppServiceProvider.php(127): Illuminate\Support\Facades\Facade::__callStatic()
#20 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Providers\AppServiceProvider->boot()
#21 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#22 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#23 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#24 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Container/Container.php(663): Illuminate\Container\BoundMethod::call()
#25 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(933): Illuminate\Container\Container->call()
#26 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(914): Illuminate\Foundation\Application->bootProvider()
#27 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}()
#28 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(915): array_walk()
#29 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#30 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(242): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap()
#31 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Foundation\Application->bootstrapWith()
#32 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(160): Illuminate\Foundation\Http\Kernel->bootstrap()
#33 /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#34 /var/www/controlpanel/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle()
#35 {main}
[2023-04-23 15:20:37] production.INFO: array (
  0 =>
  array (
    'column' => '6',
    'dir' => 'desc',
  ),
)
[2023-04-23 15:37:30] production.INFO: array (
  0 =>
  array (
    'column' => '6',
    'dir' => 'desc',
  ),
)
```

**Comment by GeckoBoy84** [comment]
This is not the place for support. Head to our discord server.

**Comment by 1day2die** [comment]
https://discord.com/invite/4Y6HjD2uyU
